# Generated by Django 5.1.1 on 2024-10-08 12:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Emplacement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Famille',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Inventaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('annee', models.IntegerField(default=2024, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Origine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('designation', models.CharField(max_length=255)),
                ('code_article', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('emplacement', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cnc_app.emplacement')),
                ('famille', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cnc_app.famille')),
                ('inventaire', models.ForeignKey(default=2024, on_delete=django.db.models.deletion.CASCADE, to='cnc_app.inventaire')),
                ('origine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cnc_app.origine')),
            ],
        ),
        migrations.CreateModel(
            name='DetailInventaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantite', models.IntegerField()),
                ('etat', models.CharField(default='Moyen', max_length=50)),
                ('date', models.DateField(auto_now_add=True)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cnc_app.article')),
                ('inventaire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cnc_app.inventaire')),
            ],
        ),
    ]
