# Generated by Django 5.1.1 on 2024-10-14 11:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cnc_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detailinventaire',
            name='status_article',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='cnc_app.statusarticle'),
        ),
    ]
