# Generated by Django 5.1.1 on 2024-10-09 10:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cnc_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='famille',
        ),
        migrations.CreateModel(
            name='Designation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=255, unique=True)),
                ('famille', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cnc_app.famille')),
            ],
        ),
        migrations.AlterField(
            model_name='article',
            name='designation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cnc_app.designation'),
        ),
    ]
