# Generated by Django 5.1.1 on 2024-10-10 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cnc_app', '0002_remove_article_famille_designation_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='designation',
            name='famille',
        ),
        migrations.AddField(
            model_name='article',
            name='famille',
            field=models.CharField(choices=[('materiel_informatique', 'Matériel Informatique'), ('materiel_bureautique', 'Matériel Bureautique'), ('materiel_medical', 'Matériel Médical'), ('materiel_transport', 'Matériel Transport'), ('equipement_medical', 'Équipement Médical'), ('autre_materiel_technique', 'Autre Matériel Technique')], default='materiel_informatique', max_length=50),
        ),
    ]
