# Generated by Django 5.1.1 on 2024-10-10 15:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cnc_app', '0003_remove_designation_famille_article_famille'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='famille',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cnc_app.famille'),
        ),
        migrations.AlterField(
            model_name='article',
            name='inventaire',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cnc_app.inventaire'),
        ),
    ]
